#Uranus config
uranus:
  fdep:
    host: localhost

# Spring config
spring:
  activemq:
    broker-url: tcp://192.168.200.202:61616
    user: region-cdm-test
    password: region-cdm-test
    in-memory: false
    pool:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://${uranus.fdep.host}:3306/uranus_fdep?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Mf#llsy78g
