#Uranus config
uranus:
  fdep:
    host: release-rhel.cscn.net

# Spring config
spring:
  activemq:
    broker-url: tcp://${uranus.fdep.host}:61616
    user: admin
    password: admin
    in-memory: false
    pool:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${uranus.fdep.host}:3306/uranus_fdep?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Mf#llsy78g
